Feature/skeleton loader
ODIN-PROTOCOL/odin-blockchain-scan pull request #11
Opened 2022-06-21 16:09 UTC by nikita1tup

2022-06-23 13:08 UTC, ArtSuslov requested changes

2022-06-23 13:08 UTC, ArtSuslov commented on src/views/AccountsItem.vue
> +            :tableSize="10"
use kebab-case and no v-bind with primitives

2022-06-23 13:08 UTC, ArtSuslov commented on src/views/ValidatorsView.vue
> +      window.addEventListener('resize', updateWidth)
removing event listeners is a [good practice](https://stackoverflow.com/questions/6033821/do-i-need-to-remove-event-listeners-before-removing-elements)

2022-06-24 10:24 UTC, nikita1tup commented on src/helpers/helpers.ts
> +export const duplicateArrayNCount = (
+

2022-06-27 12:45 UTC, ArtSuslov requested changes

2022-06-27 12:45 UTC, ArtSuslov commented on src/components/CopyText.vue
> +    @include ellipsis();
use placeholders [when possible](https://medium.com/@linker21/scss-placeholders-vs-mixins-fe79b9dbb6d5)

2022-06-27 12:51 UTC, merged