Update table
ODIN-PROTOCOL/odin-blockchain-scan pull request #18
Opened 2022-08-19 14:07 UTC by mr-pavlenko

- Update the table title, table and pagination design for Transactions / Blocks / Validators / Top Accounts pages
- Update Search bar on Validators page
- Fix the issue with the layout

<img width="1726" alt="Screenshot 2022-08-19 at 17 03 56" src="https://user-images.githubusercontent.com/29440427/185636588-50f4457b-c087-4ed6-ab35-18b688d814b1.png">
<img width="1728" alt="Screenshot 2022-08-19 at 17 04 09" src="https://user-images.githubusercontent.com/29440427/185636603-3ba85a2b-5a90-4c4e-8aca-f239c6524234.png">
<img width="1727" alt="Screenshot 2022-08-19 at 17 04 19" src="https://user-images.githubusercontent.com/29440427/185636608-f22b9c59-31e6-4e72-8056-851f8b98073c.png">
<img width="1728" alt="Screenshot 2022-08-19 at 17 04 32" src="https://user-images.githubusercontent.com/29440427/185636613-e164e565-653e-43c5-9d78-41f6fad4c7f0.png">
<img width="1492" alt="Screenshot 2022-08-19 at 17 04 42" src="https://user-images.githubusercontent.com/29440427/185636618-f1f21967-e4a9-4f89-b728-cb4a3523774a.png">
<img width="1439" alt="Screenshot 2022-08-19 at 17 04 47" src="https://user-images.githubusercontent.com/29440427/185636623-be857e99-7c38-4ec6-9be3-09edb6ebc80c.png">
<img width="1454" alt="Screenshot 2022-08-19 at 17 04 56" src="https://user-images.githubusercontent.com/29440427/185636626-5fd45d66-4ca8-40fd-94d7-b80faf04e0d8.png">

2022-08-19 19:39 UTC, nikita1tup requested changes

2022-08-19 19:39 UTC, nikita1tup commented on src/styles/tables.scss
>    &__row {
waterfall

2022-08-19 19:39 UTC, nikita1tup commented on src/styles/views.scss
> +    &-info {
if this modifier you need write &--prefix

2022-08-19 19:39 UTC, nikita1tup commented on src/views/BlocksList.vue
> +          {{ blocksCount.toLocaleString() }} blocks found
why you used toLocaleString?

2022-08-19 19:39 UTC, nikita1tup commented on src/components/TxLine.vue
> +        ]"
looks bad

2022-08-19 19:39 UTC, nikita1tup commented on src/components/AccountsLine.vue
> +const accountOdinPercentage = Number(props.account.odin_percent).toFixed(8)
we use only 6 decimal and use trimLeadingZeros func

2022-08-19 19:39 UTC, nikita1tup commented on src/components/ValidatorStatus.vue
> -  }
it's use in Validator Descriptions, better to remove after you redesign everywhere

2022-08-20 11:35 UTC, ArtSuslov requested changes

2022-08-20 11:35 UTC, ArtSuslov commented on src/styles/views.scss
> +  &__main-view-table-header {
it's better to get rid of such selectors, use the full block__element name instead of waterfalls. Much easier to search through project

2022-08-22 08:00 UTC, mr-pavlenko commented on src/views/BlocksList.vue
> +          {{ blocksCount.toLocaleString() }} blocks found
According to mockup the digits should be separate by comma
<img width="425" alt="Screenshot 2022-08-22 at 10 59 38" src="https://user-images.githubusercontent.com/29440427/185870171-18c82f21-562b-41fb-9d03-284cf32ed88b.png">

2022-08-22 08:35 UTC, mr-pavlenko commented on src/styles/views.scss
> +    &-info {
It is not a modifier, but the named element. Anyway, fixed

2022-08-22 08:36 UTC, mr-pavlenko commented on src/styles/tables.scss
>    &__row {
done

2022-08-22 08:36 UTC, mr-pavlenko commented on src/components/TxLine.vue
> +        ]"
Moved the logic to computed variable

2022-08-22 08:36 UTC, mr-pavlenko commented on src/components/AccountsLine.vue
> +const accountOdinPercentage = Number(props.account.odin_percent).toFixed(8)
Ok, using the function now

2022-08-22 08:36 UTC, mr-pavlenko commented on src/styles/views.scss
> +  &__main-view-table-header {
done

2022-08-22 08:37 UTC, mr-pavlenko commented on src/components/ValidatorStatus.vue
> -  }
Actually, both pages are using the same component, so it is changed for both pages. Keeping these styles don't change anything.

2022-08-22 16:09 UTC, nikita1tup requested changes

2022-08-22 16:09 UTC, nikita1tup commented on src/components/TxLine.vue
> +  if (_transition.value.amount !== '-') {
why u can't use props.transition.amount

2022-08-22 16:09 UTC, nikita1tup commented on src/styles/tables.scss
>    &__row {
.app-table__row and remove nesting

2022-08-22 16:09 UTC, nikita1tup commented on src/styles/views.scss
> +    font-size: 16px;
rem

2022-08-22 21:09 UTC, stas-veriho commented on src/styles/tables.scss
> +    &-date {
This is not a modifier, just another element with a different class (this similar with &-txt below)

2022-08-22 21:09 UTC, mr-pavlenko commented on src/styles/tables.scss
> +    &-date {
This is not a modifier, just another element with a different class (this similar with &-txt below)

2022-08-22 21:16 UTC, mr-pavlenko commented on src/styles/views.scss
> +  .app__main-view-table-header-prefix {
done

2022-08-22 21:16 UTC, mr-pavlenko commented on src/styles/tables.scss
>    &__row {
done

2022-08-22 21:16 UTC, mr-pavlenko commented on src/styles/views.scss
> +    font-size: 16px;
done

2022-08-22 21:16 UTC, mr-pavlenko commented on src/components/TxLine.vue
> +  if (_transition.value.amount !== '-') {
correct, fixed

2022-08-22 21:59 UTC, nikita1tup commented on src/styles/tables.scss
> +q
?

2022-08-23 07:22 UTC, mr-pavlenko commented on src/styles/tables.scss
> +q
removed

2022-08-23 09:47 UTC, merged