Restyle Account Detail page
ODIN-PROTOCOL/odin-blockchain-scan pull request #30
Opened 2022-09-05 20:47 UTC by mr-pavlenko

- Restyle Accounts and Account Details pages
- Fix adaptive design for the tables

![screencapture-localhost-8080-accounts-2022-09-05-23_44_31](https://user-images.githubusercontent.com/29440427/188511093-5f6b231f-59dd-4c3e-820e-cc6b4c08fdb6.png)
![screencapture-localhost-8080-accounts-2022-09-05-23_44_48](https://user-images.githubusercontent.com/29440427/188511104-4f6d76f1-4a53-4f27-a43a-481ef122b46d.png)
![screencapture-localhost-8080-accounts-odin1cgfdwtrqfdrzh4z8rkcyx8g4jv22v8wgs39amj-2022-09-05-23_45_09](https://user-images.githubusercontent.com/29440427/188511108-7204984b-9c69-422f-905e-f8f927a9dfaf.png)
![screencapture-localhost-8080-accounts-odin1cgfdwtrqfdrzh4z8rkcyx8g4jv22v8wgs39amj-2022-09-05-23_45_32](https://user-images.githubusercontent.com/29440427/188511111-dba107bc-8929-42b1-b0a0-5d7f35f65bce.png)

2022-09-05 21:03 UTC, nikita1tup requested changes

2022-09-05 21:03 UTC, nikita1tup commented on src/components/AccountsLine.vue
> +}
bad practice, create new class in AccountsLine component and don't change app-table classes

2022-09-05 21:32 UTC, mr-pavlenko commented on src/components/AccountsLine.vue
> +}
I think these classes are supposed to be changed, because for example in tables.scss for head display: none by default that means this needs to be changed in the consumer component. Do you mean .app_table__title only or all three classes?

2022-09-06 15:07 UTC, nikita1tup requested changes

2022-09-06 15:07 UTC, nikita1tup commented on src/views/TopAccounts.vue
> +    margin-bottom: 0rem;
0

2022-09-06 15:07 UTC, nikita1tup commented on src/views/TopAccounts.vue
> +  box-shadow: 0px 4px 24px rgba(8, 87, 172, 0.12);
px and var

2022-09-06 15:07 UTC, nikita1tup commented on src/views/TopAccounts.vue
> +  background: #ffffff;
var

2022-09-06 15:07 UTC, nikita1tup commented on src/components/ThemeSwitch.vue
> +const props = defineProps<{ theme: string; toggleTheme }>()
toggleTheme ?

2022-09-06 17:49 UTC, mr-pavlenko commented on src/components/ThemeSwitch.vue
> +const props = defineProps<{ theme: string; toggleTheme }>()
Function. Will fix in in scope of the implementing portal here.

2022-09-06 17:50 UTC, mr-pavlenko commented on src/views/TopAccounts.vue
> +  background: #ffffff;
done

2022-09-06 17:50 UTC, mr-pavlenko commented on src/views/TopAccounts.vue
> +    margin-bottom: 0rem;
done

2022-09-06 18:37 UTC, merged