fix clear button in searchbar
ODIN-PROTOCOL/odin-blockchain-scan pull request #8
Opened 2022-06-13 14:23 UTC by OscarFlay96

Made a custom button to clear the text from the searchbar

2022-06-20 09:14 UTC, nikita1tup commented on src/components/SearchBar/SearchBar.vue
> +        handleNotificationInfo(error as Error, TYPE_NOTIFICATION.failed)
remove this

2022-06-30 10:54 UTC, ArtSuslov requested changes

2022-06-30 10:54 UTC, ArtSuslov commented on src/components/SearchBar/SearchBar.vue
> +            'search-bar__input': true,
?

2022-06-30 11:01 UTC, ArtSuslov requested changes

2022-07-19 10:56 UTC, OscarFlay96 commented on src/components/SearchBar/SearchBar.vue
> +        <template v-if="searchedText">
I tried in this commit https://github.com/ODIN-PROTOCOL/odin-web/pull/13/commits/85f843b9a779336aa6d09ded7781b5581b8bfe7d and if this is what you request we still need to duplicate a lot of styles because the styles are in the wrapper level not at button or input level

2022-07-26 11:20 UTC, merged